### ISSUE TITLE
Add example Xplat CLI commands for manual part

### ISSUE THREAD

**Issue by edevil** [sercand/azure-kubernetes#1]
Thanks for the example. In fact I have also written an howto of how to setup a Kube cluster on Azure using Terraform+Ansible, but I didn't use the cbr0 bridge (https://github.com/edevil/kubernetes-deployment).

In this deployment script it is mentioned that there is a manual step that must be performed

```
  You need to associate each subnet to created route-table
```

Could you provide an example of this step using the Azure xplat CLI? Thanks.

**Comment by sercand** [comment]
No need to extra script, I have found how to do it with terraform after looking at documentation.

**Comment by edevil** [comment]
Cool! By manually adding these routes do we still need Flannel's overlay network?

**Comment by sercand** [comment]
I think no, just disable flannel. Docker running with with "--bridge=cbr0 --iptables=false --ip-masq=false" options
